apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name:  "http-ingress-mapping-egress-http-request-response477"
  description: 'HTTP request/response'
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - rest
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: "lowcode"
  system: servicemesh
  providesApis:
    - "http-ingress-mapping-egress-http-request-response477"
